package com.nerdygadgets.monitoring.data.entities;

import com.nerdygadgets.monitoring.data.enums.LogType;
import javax.persistence.*;

/**
 * This entity class is used for the status logs, generated by the Logging application on each active component
 * (see the ERD scheme in the Technical Design document for a better overview)
 */
@Entity
@Table(name = "log")
public class Log extends BaseEntity {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "componentDetailId")
    private ComponentDetail componentDetail;

    @Enumerated(EnumType.STRING)
    private LogType type;
    @Column(length = 500)
    private String error;
    private Boolean isResolved = null;

    public ComponentDetail getComponentDetail() {
        return componentDetail;
    }

    public void setComponentDetail(ComponentDetail componentDetail) {
        this.componentDetail = componentDetail;
    }

    public LogType getType() {
        return type;
    }

    public void setType(LogType type) {
        this.type = type;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Boolean isResolved() {
        return isResolved;
    }

    public void setResolved(Boolean resolved) {
        isResolved = resolved;
    }
}
